export interface TermsSection {
  id: string;
  title: string;
  content: {
    paragraphs?: string[];
    lists?: {
      type: "unordered" | "ordered";
      items: string[];
    }[];
  };
}

export interface TermsContent {
  lastUpdated: string;
  pageTitle: string;
  sections: TermsSection[];
  contactInfo: {
    heading: string;
    paragraphs: string[];
    details: {
      name: string;
      email: string;
      website: string;
    };
  };
  footer: {
    acknowledgment: string;
    privacyLinkText: string;
  };
}

export const termsContent: TermsContent = {
  lastUpdated: "June 15, 2025",
  pageTitle: "Terms of Service",
  sections: [
    {
      id: "owner-description",
      title: "1. Website Owner and Service Description",
      content: {
        paragraphs: [
          'This website is owned and operated by PodSlice ("we," "us," or "our"). These Terms of Service set forth the terms and conditions under which you may use our website and services as offered by us. This website offers visitors AI-powered podcast curation and summarization services, including personalized content delivery, audio summaries, and subscription-based features.',
          "By accessing or using the website of our service, you approve that you have read, understood, and agree to be bound by these Terms.",
        ],
      },
    },
    {
      id: "eligibility",
      title: "2. Eligibility and Account Requirements",
      content: {
        paragraphs: [
          "In order to use our website and/or receive our services, you must be at least 18 years of age, or of the legal age of majority in your jurisdiction, and possess the legal authority, right and freedom to enter into these Terms as a binding agreement. You are not allowed to use this website and/or receive services if doing so is prohibited in your country or under any law or regulation applicable to you.",
          "To access certain features of our service, you may be required to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.",
        ],
      },
    },
    {
      id: "subscription",
      title: "3. Subscription Terms and Payment",
      content: {
        paragraphs: ["When subscribing to our service, you agree that:"],
        lists: [
          {
            type: "unordered",
            items: [
              "You are responsible for reading the full service description before making a commitment to subscribe",
              "You enter into a legally binding contract to purchase the service when you commit to subscribe and complete the check-out payment process",
              "Subscription fees are charged on a recurring basis according to your selected plan",
              "We reserve the right to change our prices for services displayed at any time, and to correct pricing errors that may inadvertently occur",
            ],
          },
        ],
      },
    },
    {
      id: "trial-cancellation",
      title: "4. Trial Period and Cancellation",
      content: {
        paragraphs: [
          "We offer a 14-day free trial for new subscribers. During the trial period, you have full access to our service features. At the end of the trial period, your subscription will automatically convert to a paid plan unless you cancel before the trial ends.",
          "You may cancel your subscription at any time through your account settings. Cancellations will take effect at the end of your current billing period. No refunds will be provided for partial months of service.",
        ],
      },
    },
    {
      id: "service-modifications",
      title: "5. Service Modifications",
      content: {
        paragraphs: [
          "We may, without prior notice, change the services; stop providing the services or any features of the services we offer; or create limits for the services. We may permanently or temporarily terminate or suspend access to the services without notice and liability for any reason, or for no reason.",
        ],
      },
    },
    {
      id: "warranties",
      title: "6. Service Warranties and Limitations",
      content: {
        paragraphs: [
          'Our service is provided "as is" and "as available" without warranties of any kind. We do not guarantee that our service will be uninterrupted, secure, or error-free. We are not responsible for the accuracy, completeness, or usefulness of any content generated by our AI systems.',
          "To the maximum extent permitted by applicable law, in no event shall PodSlice be liable for any indirect, punitive, incidental, special, consequential or exemplary damages, including without limitation, damages for loss of profits, goodwill, use, data or other intangible losses, arising out of or relating to the use of, or inability to use, the service.",
        ],
      },
    },
    {
      id: "intellectual-property",
      title: "7. Intellectual Property Rights",
      content: {
        paragraphs: [
          "The Service and all materials therein or transferred thereby, including, without limitation, software, images, text, graphics, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music and all Intellectual Property Rights related thereto, are the exclusive property of PodSlice. Except as explicitly provided herein, nothing in these Terms shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works thereof.",
          "You retain ownership of any content you upload to our service. By uploading content, you grant us a limited license to use, process, and display your content solely for the purpose of providing our service to you.",
        ],
      },
    },
    {
      id: "suspension-termination",
      title: "8. Account Suspension and Termination",
      content: {
        paragraphs: [
          "We may permanently or temporarily terminate or suspend your access to the service without notice and liability for any reason, including if in our sole determination you violate any provision of these Terms or any applicable law or regulations. You may discontinue use and request to cancel your account and/or any services at any time.",
          "Notwithstanding anything to the contrary in the foregoing, with respect to automatically-renewed subscriptions to paid services, such subscriptions will be discontinued only upon the expiration of the respective period for which you have already made payment.",
        ],
      },
    },
    {
      id: "indemnification",
      title: "9. Indemnification",
      content: {
        paragraphs: [
          "You agree to indemnify and hold PodSlice harmless from any demands, loss, liability, claims or expenses (including attorneys' fees), made against them by any third party due to, or arising out of, or in connection with your use of the website or any of the services offered on the website.",
        ],
      },
    },
    {
      id: "liability-limitation",
      title: "10. Limitation of Liability",
      content: {
        paragraphs: [
          "To the maximum extent permitted by applicable law, PodSlice assumes no liability or responsibility for any (i) errors, mistakes, or inaccuracies of content; (ii) personal injury or property damage, of any nature whatsoever, resulting from your access to or use of our service; and (iii) any unauthorized access to or use of our secure servers and/or any and all personal information stored therein.",
        ],
      },
    },
    {
      id: "terms-modifications",
      title: "11. Terms Modifications",
      content: {
        paragraphs: [
          "We reserve the right to modify these terms from time to time at our sole discretion. Therefore, you should review these page periodically. When we change the Terms in a material manner, we will notify you that material changes have been made to the Terms. Your continued use of the Website or our service after any such change constitutes your acceptance of the new Terms. If you do not agree to any of these terms or any future version of the Terms, do not use or access (or continue to access) the website or the service.",
        ],
      },
    },
    {
      id: "communications-marketing",
      title: "12. Communications and Marketing",
      content: {
        paragraphs: [
          "You agree to receive from time to time promotional messages and materials from us, by mail, email or any other contact form you may provide us with (including your phone number for calls or text messages). If you don't want to receive such promotional materials or notices – please just notify us at any time.",
        ],
      },
    },
    {
      id: "governing-law",
      title: "13. Governing Law and Dispute Resolution",
      content: {
        paragraphs: [
          "These Terms is to be governed, interpreted and implemented in accordance with the laws of South Africa.",
        ],
        lists: [
          {
            type: "ordered",
            items: [
              "You consent to the non-exclusive jurisdiction of the High Court of South Africa, Western Cape Local Division, Cape Town for any proceedings arising out of or in connection with these Terms.",
              "The grant of any indulgence, extension of time or relaxation of any provision by Stitch under these Terms shall not constitute a waiver of any right by us or prevent or adversely affect the exercise by us of any existing or future right of ours.",
              "Any provision in these Terms which is or may become illegal, invalid or unenforceable shall be ineffective to the extent of such prohibition or unenforceability and shall be treated as having not been written and severed from the balance of these Terms, without invalidating the remaining provisions of these Terms or affecting the validity or enforceability of such provision.",
              "Any provision in these Terms which is or may become illegal, invalid or unenforceable shall be ineffective to the extent of such prohibition or unenforceability and shall be treated as having not been written and severed from the balance of these Terms, without invalidating the remaining provisions of these Terms or affecting the validity or enforceability of such provision.",
              "You may not cede any or all of its rights or delegate any or all of its obligations under these Terms.",
            ],
          },
        ],
      },
    },
  ],
  contactInfo: {
    heading: "14. Contact Information",
    paragraphs: [
      "For questions about these Terms of Service, please contact us at:",
    ],
    details: {
      name: "The Podslice Team",
      email: "notifications@podslice.ai",
      website: "www.podslice.ai",
    },
  },
  footer: {
    acknowledgment:
      "By using our service, you acknowledge that you have read and understood these Terms of Service and agree to be bound by them.",
    privacyLinkText: "View our Privacy Policy",
  },
};
