[build]
  command = "npx prisma generate && pnpm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APP_URL,GOOGLE_CLOUD_STORAGE_BUCKET_NAME,EMAIL_FROM,NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,EMAIL_HOST,EMAIL_USER,NEXT_DEFAULT_URL,DATABASE_URL,CLERK_SECRET_KEY,GOOGLE_GENERATIVE_AI_API_KEY,XAI_API_KEY,OPENAI_API_KEY,STRIPE_SECRET_KEY,EMAIL_PASSWORD,INNGEST_EVENT_KEY,INNGEST_SIGNING_KEY"
  SECRETS_SCAN_OMIT_PATHS = ".next/**/*,node_modules/**/*"
