[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APP_URL,GOOGLE_CLOUD_STORAGE_BUCKET_NAME,EMAIL_FROM,NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,EMAIL_HOST"
