onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@clerk/shared"
  - "@prisma/client"
  - "@prisma/engines"
  - core-js
  - esbuild
  - prisma
  - protobufjs
  # Removed mdns2 and zmq as they're not needed for production builds
