export const myEpisodesContent = {
	header: {
		title: "Your Generated Summaries",
		description:
			"View your recently generated summaries. This content was generated by you using our AI engine. It is not curated by us. Play an episode to listen to it. or View more details about the episode by clicking the title  of the episode.",
		cta: {
			text: "Generate Episode",
			href: "/generate-my-episodes",
		},
		inactiveMessage:
			"Your membership is inactive. Episodes you created are no longer accessible. Reactivate to generate and access episodes again.",
	},
} as const;
