/**
 * Episodes page content
 * Centralized static copy and configuration for the episodes page
 */

export const episodesPageContent = {
  header: {
    title: "Bundled Content",
    description:
      "The generated content from your active bundle. Click an episode to play it. This content is generated by our AI and is not curated by us. New episodes are generated weekly. You can filter by bundle type to see all episodes from your active bundle.",
  },
  filters: {
    label: "Filter by:",
    selectPlaceholder: "Select bundle type",
    options: {
      all: "All Bundles",
      curated: "Curated Bundles",
      shared: "Shared Bundles",
    },
  },
  sections: {
    all: {
      title: "All Bundled Episodes",
      description:
        "The generated content from all your active bundles. You can filter by bundle type to see all episodes from your active bundle.",
    },
    curated: {
      title: "Curated Bundle Episodes",
      description:
        "The weekly generated content from podslice curated  bundles you are subscribed to.",
    },
    shared: {
      title: "Shared Bundle Episodes",
      description:
        "The generated content from publically shared  bundles you are subscribed to.",
    },
  },
  states: {
    error: {
      title: "Unable to Load Episodes",
      button: "Try Again",
    },
    empty: {
      title: "No Episodes Available",
      description:
        "There are no episodes available at the moment. Create a personal feed or select a bundle to start getting episodes.",
    },
  },
} as const;
