"use client";

import { Label } from "@radix-ui/react-label";
import { AlertCircle, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { EpisodeList } from "@/components/episode-list";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { CardContent } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { H3 } from "@/components/ui/typography";
import type { Episode } from "@/lib/types";
import { useAudioPlayerStore } from "@/store/audioPlayerStore";

type BundleType = "all" | "curated" | "shared";

export default function EpisodesPage() {
	const [episodes, setEpisodes] = useState<Episode[]>([]);
	const [isLoading, setIsLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);
	const [bundleType, setBundleType] = useState<BundleType>("all");
	const { setEpisode } = useAudioPlayerStore();

	const fetchEpisodes = useCallback(async (type: BundleType) => {
		try {
			setIsLoading(true);
			setError(null);

			const response = await fetch(`/api/episodes?bundleType=${type}&ts=${Date.now()}`, { cache: "no-store" });

			if (!response.ok) {
				throw new Error(`Failed to load episodes. Server responded with status ${response.status}.`);
			}

			const episodesData = await response.json();
			setEpisodes(episodesData);
		} catch (error) {
			console.error("Error fetching episodes:", error);
			setError(error instanceof Error ? error.message : "An unexpected error occurred while loading episodes.");
		} finally {
			setIsLoading(false);
		}
	}, []);

	useEffect(() => {
		fetchEpisodes(bundleType);
	}, [bundleType, fetchEpisodes]);

	const handleBundleTypeChange = (value: string) => {
		setBundleType(value as BundleType);
	};

	const handlePlayEpisode = (episode: Episode) => {
		console.log("Episodes - Setting episode:", episode);
		setEpisode(episode);
	};

	return (
		<div className="min-w-full w-screen md:w-full md:episode-card-wrapper">
			<PageHeader
				title="Bundled Content"
				description="The generated content from your active bundle. Click an episode to play it. This content is generated by our AI and is not curated by us. New episodes are generated weekly. You can filter by bundle type to see all episodes from your active bundle.	"
			/>

			{isLoading ? (
				<div className="px-6 py-14 md:px-8 md:pt-12 md:mt-4 border-1 border-input-border rounded-4xl mx-auto bg-big-card">
					<div className="flex flex-col gap-4	">
						<Skeleton className="bg-[#2f4383]/30 h-[45px] w-full animate-pulse" />
						<Skeleton className="bg-[#2f4383]/30 h-[45px] w-full animate-pulse max-w-1/2" />
						<CardContent className="md:episode-card-wrapper-dark space-y-2 flex-col flex w-full">
							<Skeleton className="bg-[#2f4383]/30 h-[105px] w-full animate-pulse" />
							<Skeleton className="bg-[#2f4383]/30 h-[105px] w-full animate-pulse" />
							<Skeleton className="bg-[#2f4383]/30 h-[105px] w-full animate-pulse" />
							<Skeleton className="bg-[#2f4383]/30 h-[105px] w-full animate-pulse" />
							<Skeleton className="bg-[#2f4383]/30 h-[105px] w-full animate-pulse" />
						</CardContent>
					</div>
				</div>
			) : error ? (
				<div className="md:max-w-2xl md:mx-auto mt-8">
					<Alert variant="destructive">
						<AlertCircle className="h-4 w-4" />
						<AlertTitle>Unable to Load Episodes</AlertTitle>
						<AlertDescription className="mt-2">{error}</AlertDescription>
					</Alert>
					<div className="mt-6 text-center">
						<Button onClick={() => fetchEpisodes(bundleType)} variant="outline">
							<RefreshCw className="h-4 w-4 mr-2" />
							Try Again
						</Button>
					</div>
				</div>
			) : episodes.length === 0 ? (
				<div className="w-full  max-w-[1000px] md:mx-auto mt-0">
					<Alert>
						<AlertTitle>No Episodes Available</AlertTitle>
						<AlertDescription className="mt-2">There are no episodes available at the moment. Create a personal feed or select a bundle to start getting episodes.</AlertDescription>
					</Alert>
				</div>
			) : (
				<div className="flex md:rounded-3xl  md:bg-bigcard px-6  py-12 md:mt-4 flex-col justify-start items-start w-screen md:w-screen max-w-full gap-4">
					<div className="w-full flex flex-col items-start md:items-end justify-end gap-1 mb-6">
						<Label htmlFor="bundle-type-select" className="text-sm font-medium text-primary-foreground text-left pl-2 mb-2">
							Filter by:
						</Label>
						<Select value={bundleType} onValueChange={handleBundleTypeChange}>
							<SelectTrigger id="bundle-type-select">
								<SelectValue placeholder="Select bundle type" />
							</SelectTrigger>
							<SelectContent>
								<SelectItem value="all">All Bundles</SelectItem>
								<SelectItem value="curated">Curated Bundles</SelectItem>
								<SelectItem value="shared">Shared Bundles</SelectItem>
							</SelectContent>
						</Select>
					</div>
					<H3 className="font-medium mb-4 text-primary-foreground">
						{bundleType === "all" && "All Bundled Episodes"}
						{bundleType === "curated" && "Curated Bundle Episodes"}
						{bundleType === "shared" && "Shared Bundle Episodes"}
					</H3>
					<EpisodeList episodes={episodes} onPlayEpisode={handlePlayEpisode} />
				</div>
			)}
		</div>
	);
}
