// Import Prisma types and enums (now as a value too)
import { PlanGate, type Prisma, type FeedbackRating as PrismaFeedbackRating, UserRole } from "@prisma/client";

// Base scalar model shapes derived from Prisma payloads (compatible with Prisma v6)
export type User = Prisma.$UserPayload["scalars"];
export type UserCurationProfile = Prisma.$UserCurationProfilePayload["scalars"];
export type Podcast = Prisma.$PodcastPayload["scalars"];
export type Bundle = Prisma.$BundlePayload["scalars"];
export type Episode = Prisma.$EpisodePayload["scalars"];
export type BundlePodcast = Prisma.$BundlePodcastPayload["scalars"];
export type ProfilePodcast = Prisma.$ProfilePodcastPayload["scalars"];
export type Notification = Prisma.$NotificationPayload["scalars"];
export type Subscription = Prisma.$SubscriptionPayload["scalars"];
export type EpisodeFeedback = Prisma.$EpisodeFeedbackPayload["scalars"];
export type FeedbackRating = PrismaFeedbackRating;
export type UserEpisode = Prisma.$UserEpisodePayload["scalars"];
export type UserIngestionConfig = Prisma.$UserIngestionConfigPayload["scalars"];
export { UserRole };

// Custom types that combine Prisma types with relations
export type UserCurationProfileWithRelations = UserCurationProfile & {
	selectedBundle?: (Bundle & { podcasts: Podcast[] }) | null;
	episodes: Episode[];
};

// Source type for podcast sources
export interface Source {
	id: string;
	name: string;
	url: string;
	image_url?: string;
}

export type SubscriptionWithRelations = Subscription & {
	user: User;
	paymentProcessor: "paddle";
	planType: PlanGate;
	status: "trialing" | "active" | "cancelled";
	currentPeriodStart: Date;
	currentPeriodEnd: Date;
	trialStart: Date;
	trialEnd: Date;
	canceledAt: Date;
	cancelAtPeriodEnd: boolean;
};

// --- New Branded Type for Product Plans ---
type ValidProductPlan = "Casual Listener" | "Free Slice" | "Curate Control";

export type ProductPlan = ValidProductPlan & { readonly __brand: unique symbol };

export const productPlanToPlanGateMap: Record<ValidProductPlan, PlanGate> = {
	"Casual Listener": PlanGate.CASUAL_LISTENER,
	"Free Slice": PlanGate.FREE_SLICE,
	"Curate Control": PlanGate.CURATE_CONTROL,
};

export interface PlanTier {
	planId: PlanGate;
	productTitle: string;
	icon: string;
	description: string;
	features: string[];
	featured: boolean;
	priceId: string;
	episodeLimit: number;
}

// Only keep custom types that can't be generated by Prisma
export interface FormState {
	success: boolean;
	message: string;
	error: string | null | undefined;
}

export interface IBillingFrequency {
	value: string;
	label: string;
	priceSuffix: string;
}

export type PaddleCheckoutCompletedData = {
	transaction_id: string;
	status: string;
	customer: {
		id: string;
	};
	items: {
		price_id: string;
	}[];
};
